### ISSUE TITLE
Use of greek letters and index ($\tau_m$) in he GUI 

### ISSUE THREAD

**Issue by JenuC** [flimlib/flimj-ui#1]
The indexed letter (m) of ($\tau_m$) appear as an unreadable box on the computer I'm testing. (Windows 7)

**Comment by Xanthorapedia** [comment]
Do the greek letters have the problem? Are numerical subscripts working fine?

**Comment by JenuC** [comment]
Greek letters are a more consequential problem when the image is exported and saved as a file. It is not ideal (just my opinion) if you have to use alt codes and shortcuts for opening a file from the terminal.

**Comment by Xanthorapedia** [comment]
I will change it to export plaintext named images. Do greek letters and indices in the UI pannel display correctly?

**Comment by JenuC** [comment]
The greek letters were okay (except for convenience). The subscript mostly shows as the unreadable square box on 2/3 PCs I tested (windows).
