### ISSUE TITLE
Time base incorrectly loaded from data simulated by TransGenerate

### ISSUE THREAD

**Issue by paulbarber** [flimlib/flimj-ui#10]
TransGenerate is my windows program for generating test data, it outputs ics files which can be loaded into fiji with File > import > image.
The time base is is the metadata under parameter scale, but is not picked up by FLIMJ.
The attached file exposes the issue.
[A1A2Gradient 1.zip](https://github.com/flimlib/flimj-ui/files/4693206/A1A2Gradient.1.zip)

**Comment by ctrueden** [comment]
@Xanthorapedia The https://scif.io/images/ site now lists [Gray-FLIM-datasets.zip](https://samples.scif.io/Gray-FLIM-datasets.zip), which includes the `A1A2Gradient 1` image.
