### ISSUE TITLE
Timebase re-definition

### ISSUE THREAD

**Issue by JenuC** [flimlib/flimj-ui#12]
could we use the unit of time (time for the smallest bin used) instead of range of time? For eg: instead of 10ns entered for a FLIM dataset of 256 bins, we enter: 10/256 = 0.039 ns. I am not sure time-base is the correct term because the range of FLIM data varies on different parameters. Let me know what you think.

Also, could we remove the spinbox and add the user to enter floating-point numbers as we had before? Reaching 10.0 using a spinbox that starts from 0.0 needs 100 keypresses in the current version.

**Comment by Xanthorapedia** [comment]
Great suggestions. Do you have an idea for naming the parameter? Time increment? Time bin?

**Comment by JenuC** [comment]
yes. time bin (ns) would be easy to understand.
