### ISSUE TITLE
Expect Bin all pixels to use the Intensity threshold

### ISSUE THREAD

**Issue by paulbarber** [flimlib/flimj-ui#15]
I would expect Bin all pixels to really be "Bin all pixels above the intensity threshold".

Open test2.sdt
Analyze>Lifetime>FLIMJ
Enter Time Bin (ns) = 0.039, click OK
Tick Bin all pixels
See Fit signal peaks >75,000 counts
Change Intensity Thresh. to 300 (max in image is 313)
Result: Fit graph does not show a signal of smaller amplitude that you would expect from less pixels.

tested on flimj-ui-1.0.7

**Comment by Xanthorapedia** [comment]
This should not be too hard to implement. But does it really make a difference if all that you want is an overview of the decay over the whole dataset? @paulbarber @JenuC

**Comment by paulbarber** [comment]
Maybe not. But that's how tri2 works and sometimes I use that to eplore the data. In tri2 we have a max threshold as well as a min. Low priority I guess.

**Comment by JenuC** [comment]
yeah. A preview of the intensity histogram is necessary for choosing the right fitting thresholds. In my image analyses, the high-low threshold would help quite a bit. But I can also preprocess my image before calling FLIMJ-UI and that is how I get away with it now.
