### ISSUE TITLE
Displayed result of Global analysis dependant on image cursor position

### ISSUE THREAD

**Issue by paulbarber** [flimlib/flimj-ui#16]
Open test2.sdt
Analyze>Lifetime>FLIMJ
Enter Time Bin (ns) = 0.039, click OK
Set Intensity Thresh to 50
Click Fit Dataset and wait
Click image cursor near coord (110, 110), a pixel that is below the intensity threshold. 
Change Algorithm to Global.
Result: Fit graph does not change but Res graph does change (what does Res show?). Tau numeric indicator shows zero.
Now click image cursor near (70, 100) on a pixel above the threshold.
Result: Tau numeric now shows global result (as do Z and A). Fit graph shows pixel fit as expected.

tested on flimj-ui-1.0.7

**Comment by Xanthorapedia** [comment]
Res shows the residual but should be all zero if the pixel is below intensity threshold or doesn't converge. However, it is expected behavior for Tau to show 0 for such pixels even in global mode.

**Comment by paulbarber** [comment]
ok, the Res issue is really minor. Leave till last.
