### ISSUE TITLE
A real progress bar for Fit Dataset

### ISSUE THREAD

**Issue by paulbarber** [flimlib/flimj-ui#18]
The spinner does not let the user know how long the processing will take. We could use a more traditional progress bar here.

**Comment by Xanthorapedia** [comment]
This needs the ability to probe fitting ops' execution. @ctrueden Do ops have any kind of callback mechanism we can use? Or passing in a callable from arguments is just fine?

**Comment by ctrueden** [comment]
@Xanthorapedia Right now the Ops framework does not have anything built-in for unified progress reporting. But you can do it in an ad hoc way by adding an optional parameter e.g. of interface `FitListener` to the relevant op(s). If the caller doesn't pass it (i.e. it's null), then do nothing—but if there is a non-null object, call its `fitUpdated(FitEvent)` method as appropriate to communicate progress.
