### ISSUE TITLE
Bayes fitting does not work with test file

### ISSUE THREAD

**Issue by paulbarber** [flimlib/flimj-ui#19]
This got broken recently.
Open test2.sdt
Analyze>Lifetime>FLIMJ
Set Algorithm to Bayes
Click image cursor on image data
Result: no fit or values are shown
Click Fit Dataset
Result: No result is shown

**Comment by Xanthorapedia** [comment]
I could not replicate this problem on 1.0.9. Both actions seem to give sensible results. Can you try and see if the problem still persists?

**Comment by paulbarber** [comment]
Ok, seems to be ok with 1.0.9. Great!
