### ISSUE TITLE
Add log y-scale option for the fitting panel

### ISSUE THREAD

**Issue by JenuC** [flimlib/flimj-ui#2]
- It would be nice to switch to logarithmic and linear y-scale options for the exponential fit- plot. It is visually easier to estimate fit accuracy on a linear plot. I know the residual plot helps, but not sufficient.

**Comment by Xanthorapedia** [comment]
The current version of JavaFX doesn't officially support log-scale plots. However, custom implementations are available, e.g. [this one](https://gist.github.com/kevinsdooapp/3227204).

**Comment by JenuC** [comment]
I didn't know it was this complicated. But practically, linear scale plots of exponential curves are harder to fit. especially for lower lifetimes.

**Comment by JenuC** [comment]
should I close this? this is not a feature we can provide right?

**Comment by Xanthorapedia** [comment]
We can keep it for reference. This feature can definitely be implemented, but I would like to save it for another day.

**Comment by paulbarber** [comment]
Providing a log scale should be trivial. 
If javaFX does not support it, then just do log10() of all the data and change the axis label.

Just for clarification... we always use the raw linear data to fit. The log graph would be for visualisation only. Some prefer it.

**Comment by JenuC** [comment]
We had discussed this option before. But the limitation was some users loading negative numbers. Maybe convert to log<sub>10</sub>() with an assert positive values?. This also spans into the issue of limiting Z values to positive numbers as default.

**Comment by paulbarber** [comment]
What's the argument for allowing negative numbers?
Is this because a background has been subtracted already, or another use case?

**Comment by JenuC** [comment]
It was for homo-fret/anisotropy use cases. But it is just an oversight and shouldn't matter.

**Comment by paulbarber** [comment]
ok, hard to know how to accommodate that with a log scale then. Not sure what is best.

**Comment by JenuC** [comment]
The log-transform is a good idea and has a higher priority than over-inclusive use cases. We should go ahead and try to add this option with a checkbox or similar. I had a few users demand log-scale when we asked them to use flimj. mainly, because they are used to _spcimage_ scaling for verifying fit errors. @Xanthorapedia: could you please add this transform as a visualization option and close the issue? thanks.

**Comment by Xanthorapedia** [comment]
I'm adapting Kevin Senechal's implementation linked in my first comment. It looks pretty decent tbh :laughing::
![image](https://user-images.githubusercontent.com/25558041/87625828-bb986980-c6f0-11ea-9ad4-5057853f7761.png)
Where would you like the checkbox/drop down/toggle switch? @JenuC @paulbarber

**Comment by paulbarber** [comment]
Looks great!
Do we need the log scale on Res too? @JenuC 
Will a checkbox fit in that bottom panel, to the left of Start? Maybe reduce the number of decimal places in Start and Stop to 2 or 3. "Photon Count" could be "Photons"?

**Comment by JenuC** [comment]
I think the residuals are good in a lin-scale. But maybe set the Y-range in residuals a little higher than min-max?

**Comment by Xanthorapedia** [comment]
I finally sorted out how to make the two axes (log, linear) live together in the same chart (no you can't 😬). So I implemented my own `VariableScaleAxis` that supports both scales at the same time as well as the transition animation when you switch the scale. 

I also decided to hide the toggle switch in a side panel that will appear if you hover on the plot area margin.

See if you like it 😃:

![ezgif com-optimize](https://user-images.githubusercontent.com/25558041/88239528-4675e880-cc4a-11ea-8ce2-5af1558372c8.gif)

**Comment by JenuC** [comment]
@Xanthorapedia : It looks very nice.  But from a user perspective, the new transition/animated-panel makes it difficult to adjust the END for value for fitting. I was mildly annoyed when I was not able to move the bar multiple times.

**Comment by JenuC** [comment]
> Do we need the log scale on Res too? @JenuC

@Xanthorapedia : Could we use a line instead of bubbles in the residual plot. I cannot see the residual values well in this bubble plot. I want to estimate the area above/below zero quicker. A continuous line would be my simple suggestion.

**Comment by Xanthorapedia** [comment]
@JenuC 
> Could we use a line instead of bubbles in the residual plot. I cannot see the residual values well in this bubble plot. I want to estimate the area above/below zero quicker. A continuous line would be my simple suggestion.

What about a curve with area under it filled:
![image](https://user-images.githubusercontent.com/25558041/89133403-2c0cfc00-d4e1-11ea-9ded-f765b8b8f920.png)

> I was mildly annoyed when I was not able to move the bar multiple times.

I can thin down the triggering area and add a mouse hover count down before the popup. Will that help?

**Comment by JenuC** [comment]
@Xanthorapedia : This looks neat. 
 - Dont fill the area. the visibility is more important. 
 - reduce triggering area should be enough. thkx,
cool. :)
