### ISSUE TITLE
Intensity Thresh. to be reflected in the left hand Preview image

### ISSUE THREAD

**Issue by paulbarber** [flimlib/flimj-ui#20]
Just as the kernel size is nicely reflected in the left hand preview image, it would be good for the Intensity Threshold to also be visualised there.

Threshold the preview image so that pixels below the threshold are zero.
Change the lowest entry in the LUT from black to red such that areas below the threshold are red in the preview (as in TRI2).

**Comment by Xanthorapedia** [comment]
I didn't change the LUT. Instead, I inserted an annotation pass after applying the LUT. How does it look now?
![image](https://user-images.githubusercontent.com/25558041/87868581-f6063e80-c95c-11ea-801b-7762a357c353.png)
(test2.sdt with threshold 2)

**Comment by paulbarber** [comment]
Looks great! Thanks.
