### ISSUE TITLE
Intensity threshold value to be automatically changed when Kernel Size changed

### ISSUE THREAD

**Issue by paulbarber** [flimlib/flimj-ui#21]
Issue:
When Kernel Size =0 and set Intensity Thresh. to 50 and fit, image is thresholded correctly.
Now increase Kerenl Size to 1 and fit again, image is not thresholded as before because the pixel bins now exceed the threshold. I have to reset the threshold by hand to 9*50=450.

Solution:
When Kernel Size is changed, automatically calculate the equivalent intensity threshold and put the value in the UI.

new_threshold = old_threshold * ((2 * new_ksize + 1)^2) / ((2 * old_ksize + 1)^2)

**Comment by Xanthorapedia** [comment]
That's a very neat trick. Thanks for the suggestion!
