### ISSUE TITLE
Global fit plot/result panels doesn't reflect global fit

### ISSUE THREAD

**Issue by JenuC** [flimlib/flimj-ui#5]
in the global fit model, the results and the animated fit panel doesn't show global fit curves/results. Right now, it behaves like LMA with a fixed t value.

**Comment by Xanthorapedia** [comment]
This issue is addressed in 2e96356f0933e6b426b9771a25918bae832383b4. However, the fix is to fit the pixel under the pointer with LMA since it is not possible to get the exact global results without fitting the whole dataset.

**Comment by JenuC** [comment]
I agree that the export issue of global files were fixed with 2e96356f0933e6b426b9771a25918bae832383b4 . 

But regarding extracting global results before dataset-fit: since the image is treated as a single pixel, it is possible to get this value and its accuracy without running on the dataset. The accuracy of tm in a global fit is crucial before applying on the whole image.

**Comment by Xanthorapedia** [comment]
Can you suggest a way of calculating tm without fitting the whole image?

**Comment by JenuC** [comment]
the first step for global fit is to get the t1,t2,..ti values correct. the lifetime-plot should show the sum of the entire image. This single full-image-fit needs to be optimized (visually) and then the global-dataset fit is performed with the constrained t1,t2,..ti. Right now, the global-fit-dataset fixes t1,t2,..ti values based on some pre-evaluation and performs global fit, which behaves closer to an LMA with fixed t1,t2..ti. Briefly, the global fit has to be presented in the lower panel before the entire-image fit.

**Comment by paulbarber** [comment]
Just to add to what @JenuC has written. The "sum of the entire image" is a great starting point to determine the globally fit t1,t2... so this is a great idea. Also, this sum of entire image is the equivalent of the "all pixels in mask" feature in TRI2 which I discussed with @Xanthorapedia with regard to binning - the sum of entire image being the maximum bin possible. In short, showing the sum of entire image as @JenuC suggests would solve this issue and provide an "all pixels in mask" feature that is useful for other reasons.
